name: mukUtils-v2
version: '${project.version}'
authors: [mukPlugins, SattMustDie]
main: com.mukplugins.mukutilsv2.MukUtils

commands:
  feed:
    description: "restaura a vida do jogador"

  heal:
    description: "restaura a vida do jogador"

  fly:
    description: "faz o jogador ganhar asas e voar"

  tpa:
    description: "manda um pedido de tpa para alguem"

  tpaccept:
    description: "aceita o pedido de tpa pendente"

  tpadeny:
    description: "recusa o pedido de tpa pendente"

  setwarp:
    description: "seta uma warp"

  delwarp:
    description: "deleta uma warp já existente"

  warps:
    description: "lista todas as warps disponíveis no servidor"

  warp:
    description: "teleporta o jogador para uma warp"

  kit:
    description: "dá um kit ao jogador"

  tell:
    description: "mande uma mensagem a um jogador"
